# Generated by Django 4.2.19 on 2025-03-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0014_remove_document_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filehash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
