# Generated by Django 4.2.19 on 2025-03-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0015_document_filehash'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
