# Generated by Django 4.2.19 on 2025-03-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0017_alter_document_uuid_alter_entity_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
    ]
