# Generated by Django 4.2.19 on 2025-06-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0018_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='strategic',
            field=models.BooleanField(default=False),
        ),
    ]
