# Generated by Django 4.2.19 on 2025-06-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0019_item_strategic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AddField(
            model_name='item',
            name='nextdate',
            field=models.DateField(null=True),
        ),
    ]
