# Generated by Django 4.2.19 on 2025-06-20 12:53

from django.db import migrations, models
import ne_sop_api.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0020_alter_event_options_item_nextdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ne_sop_api.utils.Utils.get_upload_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='filehash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='filename',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='size',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
