# Generated by Django 4.2.19 on 2025-06-23 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ne_sop_api', '0020_alter_event_options_item_nextdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
