# Generated by Django 4.2.19 on 2025-06-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0021_document_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='users',
        ),
    ]
