# Generated by Django 4.2.19 on 2025-06-24 07:07

from django.db import migrations, models
import ne_sop_api.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0021_document_external_url_alter_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=ne_sop_api.utils.Utils.get_upload_path),
        ),
    ]
