# Generated by Django 4.2.19 on 2025-07-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0022_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='external_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='filehash',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='items',
            field=models.ManyToManyField(related_name='documents', to='ne_sop_api.item'),
        ),
        migrations.AlterField(
            model_name='document',
            name='size',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='default-value', max_length=200),
            preserve_default=False,
        ),
    ]
